package co.com.accenture.model;

import java.util.Map;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.amazonaws.services.dynamodbv2.model.AttributeValue;

@DynamoDBTable(tableName = "Clientes")
public class Clientes {

	@DynamoDBHashKey(attributeName = "Id")
	@DynamoDBAutoGeneratedKey
	private String id;

	@DynamoDBAttribute(attributeName = "Nombres")
	private String nombres;

	@DynamoDBAttribute(attributeName = "Apellidos")
	private String apellidos;

	@DynamoDBAttribute(attributeName = "Telefono")
	private String telefono;

	@DynamoDBAttribute(attributeName = "Celular")
	private String celular;

	@DynamoDBAttribute(attributeName = "Direccion")
	private String direccion;
	
	@DynamoDBAttribute(attributeName = "Genero")
	private String genero;
	
	@DynamoDBAttribute(attributeName = "Ciudad")
	private String ciudad;
	
	@DynamoDBAttribute(attributeName = "Empresa")
	private String empresa;
	
	public String getGenero() {
		return genero;
	}

	public void setGenero(String genero) {
		this.genero = genero;
	}

	public String getCiudad() {
		return ciudad;
	}

	public void setCiudad(String ciudad) {
		this.ciudad = ciudad;
	}

	public String getEmpresa() {
		return empresa;
	}

	public void setEmpresa(String empresa) {
		this.empresa = empresa;
	}

	
	public String getId() {
		return id;
	}

	public void setId(String id) {
		this.id = id;
	}

	public String getNombres() {
		return nombres;
	}

	public void setNombres(String nombres) {
		this.nombres = nombres;
	}

	public String getApellidos() {
		return apellidos;
	}

	public void setApellidos(String apellidos) {
		this.apellidos = apellidos;
	}

	public String getTelefono() {
		return telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public Clientes(Map<String, AttributeValue> item) {
		this.id = item.get("Id") == null ? null : item.get("Id").getS();
		this.nombres = item.get("Nombres") == null ? null : item.get("Nombres").getS();
		this.apellidos = item.get("Apellidos") == null ? null : item.get("Apellidos").getS();
		this.telefono = item.get("Telefono") == null ? null : item.get("Telefono").getS();
		this.celular = item.get("Celular") == null ? null : item.get("Celular").getS();
		this.direccion = item.get("Direccion") == null ? null : item.get("Direccion").getS();
		this.genero = item.get("Genero") == null ? null : item.get("Genero").getS();
		this.ciudad = item.get("Ciudad") == null ? null : item.get("Ciudad").getS();
		this.empresa = item.get("Empresa") == null ? null : item.get("Empresa").getS();
	}

	public Clientes() {
		super();
	}

}
